FROM node:18-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем исходный код
COPY . .

# Генерируем Prisma клиент
RUN npx prisma generate

# Открываем порт
EXPOSE 5000

# Запускаем приложение в режиме разработки
CMD ["npm", "run", "dev"]